services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: discord-oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: discord
      APP_USER_PASSWORD: discord
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db/init:/container-entrypoint-initdb.d

volumes:
  oracle-data:
